ALTER TABLE T_WhsQY ALTER COLUMN WhsZH nvarchar(50);
ALTER TABLE T_CusQY ALTER COLUMN CusZH nvarchar(50);
ALTER TABLE T_SupQY ALTER COLUMN SupZH nvarchar(50);
ALTER TABLE T_SupQY ALTER COLUMN SupZZJGDM nvarchar(50);
ALTER TABLE T_SupQY ALTER COLUMN SupJXFW nvarchar(3000);
ALTER TABLE T_SupQY ALTER COLUMN SupBAJYFW nvarchar(3000);
ALTER TABLE T_SupQY ALTER COLUMN SupJYFW nvarchar(3000);
ALTER TABLE T_CusQY ALTER COLUMN CusJXFW nvarchar(3000);
ALTER TABLE T_CusQY ALTER COLUMN CusJYFW nvarchar(3000);
ALTER TABLE T_CusQY ALTER COLUMN CusBAJYFS nvarchar(3000);
ALTER TABLE T_CusQY ALTER COLUMN CusSCFW nvarchar(3000);
ALTER TABLE T_WhsQY ALTER COLUMN WhsJXFW nvarchar(3000);
ALTER TABLE T_WhsQY ALTER COLUMN WhsJYFW nvarchar(3000);

ALTER TABLE T_WhsQY ALTER COLUMN WhsZCDZ nvarchar(2000);
ALTER TABLE T_WhsQY ALTER COLUMN WhsKFDZ nvarchar(2000);
ALTER TABLE T_SupQY ALTER COLUMN SupZCDZ nvarchar(2000);
ALTER TABLE T_SupQY ALTER COLUMN SupKFDZ nvarchar(2000);
ALTER TABLE T_SupQY ALTER COLUMN SupBAKFDZ nvarchar(2000);
ALTER TABLE T_SupQY ALTER COLUMN SCAddr nvarchar(2000);
ALTER TABLE T_CusQY ALTER COLUMN CusZCDZ nvarchar(2000);
ALTER TABLE T_CusQY ALTER COLUMN CusKFDZ nvarchar(2000);
ALTER TABLE T_CusQY ALTER COLUMN CusBAKFDZ nvarchar(2000);
ALTER TABLE T_CusQY ALTER COLUMN SCAddr nvarchar(2000);
ALTER TABLE T_CK ALTER COLUMN CKDZ nvarchar(2000);


ALTER TABLE T_YLCP ALTER COLUMN CPSCDZ nvarchar(2000);
ALTER TABLE T_YLCP ALTER COLUMN ZCRAddr nvarchar(2000);