//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApparatusManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysFavorite
    {
        public int FavoriteID { get; set; }
        public string FavoriteTitle { get; set; }
        public Nullable<System.DateTime> FavoriteAddTime { get; set; }
        public string FavoriteContent { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Url { get; set; }
        public string Icon { get; set; }
    
        public virtual SysUser SysUser { get; set; }
    }
}
