//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApparatusManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysRoleResource
    {
        public int AuthorId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> ResourceId { get; set; }
        public string Authorized { get; set; }
        public string Remark { get; set; }
    
        public virtual SysResource SysResource { get; set; }
    }
}
