//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApparatusManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUser
    {
        public SysUser()
        {
            this.SysFavorite = new HashSet<SysFavorite>();
        }
    
        public int UserId { get; set; }
        public string UserAccount { get; set; }
        public string UserPassword { get; set; }
        public string UserName { get; set; }
        public string UserPhone { get; set; }
        public string UserEmail { get; set; }
        public Nullable<int> UserState { get; set; }
        public Nullable<System.DateTime> UserCreateDate { get; set; }
        public Nullable<System.DateTime> UserLastLoginTime { get; set; }
        public Nullable<int> UserCompanyID { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual ICollection<SysFavorite> SysFavorite { get; set; }
    }
}
