//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApparatusManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CGD
    {
        public T_CGD()
        {
            this.T_CGMX = new HashSet<T_CGMX>();
        }
    
        public int CGID { get; set; }
        public string CGPERSON { get; set; }
        public Nullable<System.DateTime> CGRQ { get; set; }
        public string JYPERSON { get; set; }
        public Nullable<System.DateTime> JYQR { get; set; }
        public Nullable<int> ISHG { get; set; }
        public string SQPERSON { get; set; }
        public Nullable<System.DateTime> SQRQ { get; set; }
        public string SHR { get; set; }
        public Nullable<System.DateTime> SHRQ { get; set; }
        public string SHYJ { get; set; }
        public Nullable<int> ISCG { get; set; }
        public Nullable<int> ISSH { get; set; }
        public string BZ { get; set; }
        public string CGDMC { get; set; }
        public string CGCJR { get; set; }
        public Nullable<System.DateTime> CGCJRQ { get; set; }
        public string CGDH { get; set; }
        public Nullable<double> CGTotalPrice { get; set; }
    
        public virtual ICollection<T_CGMX> T_CGMX { get; set; }
        public virtual T_FP T_FP { get; set; }
    }
}
