//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApparatusManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CGMX
    {
        public int MXID { get; set; }
        public int CPID { get; set; }
        public int CGID { get; set; }
        public Nullable<double> CPNUM { get; set; }
        public Nullable<double> CPPRICE { get; set; }
        public string CPBZ { get; set; }
        public Nullable<int> SupID { get; set; }
        public string GUID { get; set; }
        public Nullable<int> CPSCQYID { get; set; }
    
        public virtual T_CGD T_CGD { get; set; }
        public virtual T_SupQY T_SupQY { get; set; }
        public virtual T_SupQY T_SupQY1 { get; set; }
        public virtual T_YLCP T_YLCP { get; set; }
    }
}
