//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApparatusManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CKCollect
    {
        public int CollectID { get; set; }
        public int CKID { get; set; }
        public Nullable<System.DateTime> CollectDate { get; set; }
        public Nullable<double> CurWD { get; set; }
        public Nullable<double> CurSD { get; set; }
        public string CollectPerson { get; set; }
        public string Remark { get; set; }
    
        public virtual T_CK T_CK { get; set; }
    }
}
