//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApparatusManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CKD
    {
        public T_CKD()
        {
            this.T_CKMX = new HashSet<T_CKMX>();
        }
    
        public int CKID { get; set; }
        public string CKMC { get; set; }
        public string CKSQR { get; set; }
        public Nullable<System.DateTime> SQRQ { get; set; }
        public string FHR { get; set; }
        public Nullable<System.DateTime> FHRQ { get; set; }
        public string CKCHR { get; set; }
        public Nullable<System.DateTime> CHRQ { get; set; }
        public string CHBZ { get; set; }
        public Nullable<int> XSID { get; set; }
        public string CKCJR { get; set; }
        public Nullable<System.DateTime> CKCJRQ { get; set; }
        public string CKDH { get; set; }
        public Nullable<int> IsFinish { get; set; }
    
        public virtual T_XSD T_XSD { get; set; }
        public virtual ICollection<T_CKMX> T_CKMX { get; set; }
    }
}
