//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApparatusManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CPLX
    {
        public T_CPLX()
        {
            this.T_CPLX1 = new HashSet<T_CPLX>();
            this.T_YLCP = new HashSet<T_YLCP>();
        }
    
        public int LXID { get; set; }
        public string LXMC { get; set; }
        public Nullable<int> INVALID { get; set; }
        public string LXBZ { get; set; }
        public Nullable<int> PLXID { get; set; }
    
        public virtual ICollection<T_CPLX> T_CPLX1 { get; set; }
        public virtual T_CPLX T_CPLX2 { get; set; }
        public virtual ICollection<T_YLCP> T_YLCP { get; set; }
    }
}
