//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApparatusManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CusQY
    {
        public T_CusQY()
        {
            this.T_CusPerson = new HashSet<T_CusPerson>();
            this.T_CusQYZZ = new HashSet<T_CusQYZZ>();
            this.T_SHFW = new HashSet<T_SHFW>();
            this.T_THD = new HashSet<T_THD>();
            this.T_XSD = new HashSet<T_XSD>();
            this.T_XSHT = new HashSet<T_XSHT>();
        }
    
        public int CusID { get; set; }
        public string CusMC { get; set; }
        public string CusFSDB { get; set; }
        public Nullable<System.DateTime> CusZCSJ { get; set; }
        public string CusZCDZ { get; set; }
        public string CusZZJGDM { get; set; }
        public string CusDWXZ { get; set; }
        public string CusJXFW { get; set; }
        public string CusBZ { get; set; }
        public Nullable<System.DateTime> CusJYKSSJ { get; set; }
        public Nullable<System.DateTime> CusJXJSSJ { get; set; }
        public string CusKHH { get; set; }
        public string CusZH { get; set; }
        public string CusJYXKZ { get; set; }
        public Nullable<double> CusZCZB { get; set; }
        public int WhsQYID { get; set; }
        public Nullable<int> CusStatus { get; set; }
        public string CusXKZBH { get; set; }
        public string CusJYFS { get; set; }
        public string CusJYCS { get; set; }
        public string CusKFDZ { get; set; }
        public string CusJYFW { get; set; }
        public Nullable<System.DateTime> CusFZRQ { get; set; }
        public Nullable<System.DateTime> CusYXQKS { get; set; }
        public Nullable<System.DateTime> CusYXQJS { get; set; }
        public string CusZZSC { get; set; }
        public string CusLXR { get; set; }
        public string CusSFZH { get; set; }
        public string CusLXDH { get; set; }
        public Nullable<System.DateTime> JYXKZFZRQ { get; set; }
        public Nullable<System.DateTime> JYXKZYXQKS { get; set; }
        public Nullable<System.DateTime> JYXKZYXQJS { get; set; }
        public Nullable<System.DateTime> SQSKS { get; set; }
        public Nullable<System.DateTime> SQSJS { get; set; }
    
        public virtual ICollection<T_CusPerson> T_CusPerson { get; set; }
        public virtual T_WhsQY T_WhsQY { get; set; }
        public virtual ICollection<T_CusQYZZ> T_CusQYZZ { get; set; }
        public virtual ICollection<T_SHFW> T_SHFW { get; set; }
        public virtual ICollection<T_THD> T_THD { get; set; }
        public virtual ICollection<T_XSD> T_XSD { get; set; }
        public virtual ICollection<T_XSHT> T_XSHT { get; set; }
    }
}
