//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApparatusManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FKD
    {
        public int FKID { get; set; }
        public Nullable<System.DateTime> FKRQ { get; set; }
        public string FKYJ { get; set; }
        public Nullable<int> FKFLAG { get; set; }
        public Nullable<int> FWID { get; set; }
        public string BZ { get; set; }
    
        public virtual T_SHFW T_SHFW { get; set; }
    }
}
