//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApparatusManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Person
    {
        public T_Person()
        {
            this.T_XSD = new HashSet<T_XSD>();
        }
    
        public int PsID { get; set; }
        public string PsMZ { get; set; }
        public string PsSFZ { get; set; }
        public string PsXB { get; set; }
        public Nullable<System.DateTime> PsCSRQ { get; set; }
        public string PsZY { get; set; }
        public string PsXL { get; set; }
        public string PsZZ { get; set; }
        public string PsZZFJ { get; set; }
        public Nullable<int> PsQYID { get; set; }
        public string PsBZ { get; set; }
        public Nullable<int> PsISZZ { get; set; }
        public Nullable<decimal> PsLXDH { get; set; }
        public string PsZW { get; set; }
        public string PsSFZSM { get; set; }
        public string PsDZ { get; set; }
    
        public virtual T_WhsQY T_WhsQY { get; set; }
        public virtual ICollection<T_XSD> T_XSD { get; set; }
    }
}
