//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApparatusManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QYSH
    {
        public int SHID { get; set; }
        public Nullable<System.DateTime> SHSJ { get; set; }
        public string SHPS { get; set; }
        public string SHYJ { get; set; }
        public Nullable<int> SHJG { get; set; }
        public byte[] SHBZ { get; set; }
        public Nullable<int> SHQYID { get; set; }
    }
}
