//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApparatusManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RKD
    {
        public T_RKD()
        {
            this.T_RKMX = new HashSet<T_RKMX>();
        }
    
        public int RKID { get; set; }
        public string RKMC { get; set; }
        public string SQPE { get; set; }
        public Nullable<System.DateTime> SQRQ { get; set; }
        public string CKGLRY { get; set; }
        public Nullable<System.DateTime> JSRQ { get; set; }
        public Nullable<double> RKNUM { get; set; }
        public string RKBZ { get; set; }
        public string RKCJR { get; set; }
        public Nullable<System.DateTime> RKCJRQ { get; set; }
        public string RKDH { get; set; }
        public string YSDH { get; set; }
    
        public virtual ICollection<T_RKMX> T_RKMX { get; set; }
    }
}
