//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApparatusManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SHFW
    {
        public T_SHFW()
        {
            this.T_FKD = new HashSet<T_FKD>();
        }
    
        public int SHID { get; set; }
        public string FWMC { get; set; }
        public Nullable<int> KHDWID { get; set; }
        public string DZ { get; set; }
        public string LXR { get; set; }
        public string LXDH { get; set; }
        public Nullable<System.DateTime> DHRQ { get; set; }
        public Nullable<System.DateTime> JHRQ { get; set; }
        public Nullable<System.DateTime> FWRQ { get; set; }
        public Nullable<decimal> FWR { get; set; }
        public string FWLXDH { get; set; }
        public string FWNR { get; set; }
        public string BZ { get; set; }
    
        public virtual T_CusQY T_CusQY { get; set; }
        public virtual ICollection<T_FKD> T_FKD { get; set; }
    }
}
