//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApparatusManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SHD
    {
        public T_SHD()
        {
            this.T_SHMX = new HashSet<T_SHMX>();
        }
    
        public int SHID { get; set; }
        public string SHDH { get; set; }
        public string SHDMC { get; set; }
        public string SQR { get; set; }
        public Nullable<System.DateTime> SQRQ { get; set; }
        public string FHY { get; set; }
        public Nullable<System.DateTime> FHRQ { get; set; }
        public string REMARK { get; set; }
        public string SHCJR { get; set; }
        public Nullable<System.DateTime> SHCJRQ { get; set; }
        public Nullable<int> ISSH { get; set; }
    
        public virtual ICollection<T_SHMX> T_SHMX { get; set; }
    }
}
