//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApparatusManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SJZDLX
    {
        public T_SJZDLX()
        {
            this.T_BJD = new HashSet<T_BJD>();
        }
    
        public int LXID { get; set; }
        public string LXMC { get; set; }
        public Nullable<int> LXFLAG { get; set; }
        public string LXBZ { get; set; }
        public Nullable<int> FLID { get; set; }
    
        public virtual ICollection<T_BJD> T_BJD { get; set; }
        public virtual T_SJZDFL T_SJZDFL { get; set; }
    }
}
