//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApparatusManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SJZDFL
    {
        public T_SJZDFL()
        {
            this.T_SJZDLX = new HashSet<T_SJZDLX>();
        }
    
        public int FLID { get; set; }
        public string FLMC { get; set; }
        public Nullable<int> FLFLAG { get; set; }
        public string BZ { get; set; }
    
        public virtual ICollection<T_SJZDLX> T_SJZDLX { get; set; }
    }
}
