//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApparatusManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_THD
    {
        public T_THD()
        {
            this.T_THMX = new HashSet<T_THMX>();
        }
    
        public int THID { get; set; }
        public string THMC { get; set; }
        public string SQR { get; set; }
        public Nullable<System.DateTime> SQRQ { get; set; }
        public string THKHMC { get; set; }
        public Nullable<int> THQYID { get; set; }
        public string THYY { get; set; }
        public string SHR { get; set; }
        public Nullable<System.DateTime> SHRQ { get; set; }
        public string SHYJ { get; set; }
        public Nullable<int> FLAG { get; set; }
        public string BZ { get; set; }
        public Nullable<int> XSID { get; set; }
    
        public virtual T_CusQY T_CusQY { get; set; }
        public virtual T_XSD T_XSD { get; set; }
        public virtual ICollection<T_THMX> T_THMX { get; set; }
    }
}
