//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApparatusManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_XSD
    {
        public T_XSD()
        {
            this.T_CKD = new HashSet<T_CKD>();
            this.T_XSMX = new HashSet<T_XSMX>();
        }
    
        public int XSID { get; set; }
        public string XSMC { get; set; }
        public Nullable<int> KHID { get; set; }
        public string XSRY { get; set; }
        public Nullable<int> XSRID { get; set; }
        public Nullable<System.DateTime> XSRQ { get; set; }
        public Nullable<double> XSJE { get; set; }
        public string XSFHR { get; set; }
        public Nullable<System.DateTime> XSSHRQ { get; set; }
        public string XSBZ { get; set; }
        public Nullable<int> XSFLAG { get; set; }
        public string SHYJ { get; set; }
        public string XSCJR { get; set; }
        public Nullable<System.DateTime> XSCJRQ { get; set; }
        public string XSDH { get; set; }
        public Nullable<int> IsFinish { get; set; }
    
        public virtual ICollection<T_CKD> T_CKD { get; set; }
        public virtual T_CusQY T_CusQY { get; set; }
        public virtual T_Person T_Person { get; set; }
        public virtual ICollection<T_XSMX> T_XSMX { get; set; }
    }
}
