//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApparatusManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_XSHT
    {
        public int HTID { get; set; }
        public string HTBH { get; set; }
        public string HTMC { get; set; }
        public string HTLX { get; set; }
        public Nullable<int> HTQDDWID { get; set; }
        public string HTSQR { get; set; }
        public Nullable<System.DateTime> SQSJ { get; set; }
        public string HTFJ { get; set; }
        public string BZ { get; set; }
        public string SHR { get; set; }
        public Nullable<System.DateTime> SHSJ { get; set; }
        public Nullable<int> SHJG { get; set; }
        public string ZLXY { get; set; }
    
        public virtual T_CusQY T_CusQY { get; set; }
    }
}
