//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApparatusManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_XSMX
    {
        public int MXID { get; set; }
        public int CPID { get; set; }
        public Nullable<int> XSID { get; set; }
        public Nullable<int> CPSL { get; set; }
        public Nullable<double> XSJG { get; set; }
        public string XSBZ { get; set; }
        public string GUID { get; set; }
    
        public virtual T_XSD T_XSD { get; set; }
        public virtual T_YLCP T_YLCP { get; set; }
    }
}
