//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApparatusManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_YSD
    {
        public T_YSD()
        {
            this.T_YSMX = new HashSet<T_YSMX>();
        }
    
        public int YSID { get; set; }
        public string YSR { get; set; }
        public Nullable<System.DateTime> YSRQ { get; set; }
        public string YSBG { get; set; }
        public string YSFLAG { get; set; }
        public string BZ { get; set; }
        public string CGDH { get; set; }
        public string YSDH { get; set; }
        public string YSCJR { get; set; }
        public Nullable<System.DateTime> YSCJRQ { get; set; }
    
        public virtual ICollection<T_YSMX> T_YSMX { get; set; }
    }
}
